db.disease.insert({diseaseId:1,name:"Downy Mildew",description:"This disease",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:2,name:"Alternaria Leaf Spot",description:"This disease", symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:3,name:"Black Rot",description:"Black rot",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:4,name:"Black Leg",description:"The fungus",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:5,name:"Pythium Damping-Off",description:"This disease",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:6,name:"Crown Rot",description:"Caused by Phytophthora.",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:7,name:"Root Rot",description:"Caused by Phythium.",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:8,name:"Fungle Complex",description:"Plant become",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:9,name:"Alternaria Leaf Spot",description:"Developes",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:10,name:"Powdery Mildew",description:"White powdery",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:11,name:"Botrytis",description:"Occurs especially",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:12,name:"Bacterial Blight",description:"Yellowish",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});
db.disease.insert({diseaseId:13,name:"Phyllody",description:"This is an irreversible",symptoms:"This disease slows down the growth of plant",remedy:"Remedy"});