   db.nutrition.insert({nutritionId:1,cropName:'Gerbera',nutricient:"Mg",symptoms:"Yellowing between the leaf veins, sometimes with reddish brown tints and early leaf fall. Magnesium deficiency is common in tomatoes, apples, grape vines, raspberries, roses and rhododendrons.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\broccoli\broccoli_macro_Mg-magnesium.jpg",remedy:"In the short term, apply Epsom salts as a foliar feed in summer. Dilute the salts at a rate of 20g of Epsom salts per litre of water (1/3oz per pint) plus a few drops of liquid detergent. Apply two or three times at fortnightly intervals, spraying in dull weather to avoid leaf scorch. In the long term apply to the soil around the roots either Dolomite limestone (calcium-magnesium carbonate) at 100g per sq m (4oz per sq yd) or Epsom salts (magnesium sulphate) at 30g per sq m (1oz per sq yd). Dolomite limestone will make the soil more alkaline, so should not be used around ericaceous (acid-loving) plants such as rhododendrons or camellias, or where the soil is already alkaline."});
   db.nutrition.insert({nutritionId:2,cropName:'Gerbera',nutricient:"N",symptoms:"Spindly yellow plants or yellow leaves, sometimes with pink tints.",imageUrl:"",remedy:"In the long term, mulching with organic matter (such as well rotted garden compost or manure) provides a steady trickle of nitrogen to stabilise levels. In the short term, applying high nitrogen fertilisers such as sulphate of ammonia or poultry manure pellets will remedy the problem."});
   db.nutrition.insert({nutritionId:3,cropName:'Gerbera',nutricient:"K",symptoms:"Yellow or purple leaf-tints with browning at the leaf edge and poor flowering or fruiting.",imageUrl:"",remedy:"Apply high potassium fertilisers such as sulphate of potash, tomato feed or certain organic potassium sources derived from sugar beet processing."});
   db.nutrition.insert({nutritionId:4,cropName:'Gerbera',nutricient:"P",symptoms:"Slow growth and dull yellow foliage.",imageUrl:"",remedy:"Apply fertilisers such as superphosphate or bone meal."});
   db.nutrition.insert({nutritionId:5,cropName:'Gerbera',nutricient:"Mn",symptoms:"Yellowing between the leaf veins with browning of leaf edges on acid-loving plants.",imageUrl:"",remedy:"Apply chelated iron and manganese treatments, such as Sequestrene, to the soil around the plant roots. "});
   db.nutrition.insert({nutritionId:6,cropName:'Gerbera',nutricient:"Fe",symptoms:"Yellowing between the leaf veins with browning of leaf edges on acid-loving plants.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\broccoli\broccoli_micro_Fe-iron.jpg",remedy:"Apply chelated iron and manganese treatments, such as Sequestrene, to the soil around the plant roots. "});
   db.nutrition.insert({nutritionId:7,cropName:'Gerbera',nutricient:"B",symptoms:"Stunted growth and tip dieback on lettuce, brown cracks in celery; rotten swedes, turnips and celeriac; dimples in pears with brown patches underneath.",imageUrl:"",remedy:"Treat with fritted trace elements (see our advice on fertilisers) or by applying borax (disodium tetraborate) to the soil before sowing vegetables or as a foliar spray feed applied to pear trees. Soil application rates for borax are: 35g per 20 sq m (1oz per 20 sq yd). Mix well with a large quantity of light sand before spreading so that the chemical is evenly distributed. Foliar spray application rates for borax are: 70g borax in 22-litres water (2½oz in 5 gallons), plus a few drops of detergent to act as a wetting agent, sprayed at petal fall."});

   db.nutrition.insert({nutritionId:8,cropName:'Rose',nutricient:"N",symptoms:"Lighter green or yellow coloured leaves (first evident in older leaves) - some plants eg. Berries can develop red or orange colours stunted growth lower protein levels in pasture and grain Nitrogen deficiency symptoms begin as pale green leaves, often smaller than normal; and stunted, weak shoot growth",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_nitrogen.jpg",remedy:"Urea contains 46% Nitrogen.Top dressing with inorganic nitrogen fertilizer @10-20 Kg N/ha.Foliar spray of nitrogen fertilizers @ 0.5% N."});
   db.nutrition.insert({nutritionId:9,cropName:'Rose',nutricient:"P",symptoms:"Phosphorus deficiency symptoms begin with reduced growth with short, thin shoots. Leaves are small, and defoliation follows starting with the lower leaves.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_Phosphorus.jpg",remedy:"Correct soil pH by adding adjuvants.Apply p 205 @ 40-50 kg/ha as single or tripl ( phosphate.Spray with 1-2% solutiol) of triple super phosph;"});
   db.nutrition.insert({nutritionId:10,cropName:'Rose',nutricient:"K",symptoms:"Potassium deficiencies are first characterized by reduced growth, weak stems, and shoot die-back. Early symptoms may be difficult to distinguish. Leaf symptoms include dull bluish-green discolorations, particularly in the interveinal areas of the leaves, dull, general chlorosis particularly at the leaf tips and margins; then tip burning and marginal scorch on the older leaves with the leaves curling under or upwards",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_Potassium.jpg",remedy:"Normally, about 50 kg K2O/ha will be adequate for the soil deficient in potassium.Potassium may be supplied regularly in the form of potassium sulphate."});
   db.nutrition.insert({nutritionId:11,cropName:'Rose',nutricient:"Ca",symptoms:"Calcium deficiency symptoms appear initially on the young leaves and the shoot apex. New leaves are distorted with hooked tips and curled margins, which are irregular and may show brown scorching or spotting. Calcium deficiency can also cause roots of the plants to become stunted, translucent, and bulbous with dead tips.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_Calcium.jpg",remedy:"Calcium deficiency can be corrected by liming the soil in the appropriate quantity.Apply calcium containing fertilizers like gypsum or chelates etc.Calcium Chelate 1 - 4%"});
   db.nutrition.insert({nutritionId:11,cropName:'Rose',nutricient:"Mg",symptoms:"Magnesium deficiency symptoms begin with chlorosis, sometimes with red or orange coloration on the oldest leaves. As symptoms progress the older leaves shrivel and drop, the veins on the remaining leaves stay green and the interveinal areas have an orange chlorotic mottle. Growth can be much reduced.",imageUrl:"",remedy:"Spray of foliage with 1% MgSO4 solution to correct the deficiency."});
   db.nutrition.insert({nutritionId:12,cropName:'Rose',nutricient:"S",symptoms:"Symptoms of Sulfur deficiency are much like those caused by Nitrogen: reduced leaf size, stunted growth, chlorosis, orange to purplish pigmentation and delayed maturity",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_Sulfur.jpg",remedy:"Sulphur deficiency can be corrected by applying fertilizers containing sulphur like Ammonium sulphate, Sulphate of Potash.Ammonium Sulphate 24% Single Super Phosphate 12% Paramphos 15%"});
   db.nutrition.insert({nutritionId:13,cropName:'Rose',nutricient:"Fe",symptoms:"A deficiency of Iron causes a decrease in the size of chloroplasts, reduced chlorophyll and reduced photosynthesis. Symptoms include yellow or white chlorosis between green veins on younger leaves and poor vigor leading to death of the shoot tips. These symptoms are most serious in poorly drained, alkaline soils.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_iron.jpg",remedy:"Apply 10 kg/ha iron sulphate through soil; spray 0.5% FeSO4 + 0.1%citric acid; add 0.2% urea in the spray solution for better results"});
   db.nutrition.insert({nutritionId:14,cropName:'Rose',nutricient:"Mn",symptoms:"Symptoms of Manganese deficiency start as interveinal mottled chlorosis, the leaves become yellow and then develop small necrotic lesions in the most chlorotic areas. Reduced leave size and crimping of leaf margins are also possible symptoms",imageUrl:"",remedy:"Apply 10 kg/ha manganese sulphate through soil; foliar application @ 0.12 kg Mn/ha is useful"});
   db.nutrition.insert({nutritionId:15,cropName:'Rose',nutricient:"Cu",symptoms:"Copper deficiency occurs in sandy soils of the Southwest. Symptoms are variable but generally consist of a lack of vigor, smaller than normal leaves, and a bluish-green cast to the leaves.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_copper.jpg",remedy:"Small amount of soil applied CuSO4 is able to correct the copper (Cu) deficiency on calcareous soils.Apply 2 - 6 kg Cu / ha as copper sulphate once in 3 - 4 years."});
   db.nutrition.insert({nutritionId:16,cropName:'Rose',nutricient:"Zn",symptoms:"Zinc deficiency symptoms begin with interveinal chlorosis. The first leaves in the spring on trees remain small, the stems fail to elongate and the leaves appear to be in whorls or rosettes.",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_zinc.jpg",remedy:"Apply 15 kg/ha or more Zn through soil; spray 10 kg/ha ZnSO4"});
   db.nutrition.insert({nutritionId:17,cropName:'Rose',nutricient:"B",symptoms:"Boron deficiency symptoms vary between plants but some general symptoms are injury to plants meristem and actively dividing tissues and death of the apical meristem. This can lead to a bushy plant habit or the death of all buds preventing new growth",imageUrl:"E:\Fertilizers\Images\nutritiondefeciency\capsicum\cap_boron.jpg",remedy:"Spray 10 kg/ha borax or 0.2% borax through soil; foliar application of 0.1 ppm B"});
    

   db.nutrition.insert({nutritionId:18,cropName:'lily',nutricient:"N",symptoms:"Lighter green or yellow coloured leaves (first evident in older leaves) - some plants eg. Berries can develop red or orange colours stunted growth lower protein levels in pasture and grain Nitrogen deficiency symptoms begin as pale green leaves, often smaller than normal; and stunted, weak shoot growth",imageUrl:"",remedy:"Urea contains 46% Nitrogen.Top dressing with inorganic nitrogen fertilizer @10-20 Kg N/ha.Foliar spray of nitrogen fertilizers @ 0.5% N."});
   db.nutrition.insert({nutritionId:19,cropName:'lily',nutricient:"P",symptoms:"Phosphorus deficiency symptoms begin with reduced growth with short, thin shoots. Leaves are small, and defoliation follows starting with the lower leaves.",imageUrl:"",remedy:"Correct soil pH by adding adjuvants.Apply p 205 @ 40-50 kg/ha as single or tripl ( phosphate.Spray with 1-2% solutiol) of triple super phosph;"});
   db.nutrition.insert({nutritionId:20,cropName:'lily',nutricient:"K",symptoms:"Potassium deficiencies are first characterized by reduced growth, weak stems, and shoot die-back. Early symptoms may be difficult to distinguish. Leaf symptoms include dull bluish-green discolorations, particularly in the interveinal areas of the leaves, dull, general chlorosis particularly at the leaf tips and margins; then tip burning and marginal scorch on the older leaves with the leaves curling under or upwards",imageUrl:"",remedy:"Normally, about 50 kg K2O/ha will be adequate for the soil deficient in potassium.Potassium may be supplied regularly in the form of potassium sulphate."});
   db.nutrition.insert({nutritionId:21,cropName:'lily',nutricient:"Ca",symptoms:"Calcium deficiency symptoms appear initially on the young leaves and the shoot apex. New leaves are distorted with hooked tips and curled margins, which are irregular and may show brown scorching or spotting. Calcium deficiency can also cause roots of the plants to become stunted, translucent, and bulbous with dead tips.",imageUrl:"",remedy:"Calcium deficiency can be corrected by liming the soil in the appropriate quantity.Apply calcium containing fertilizers like gypsum or chelates etc.Calcium Chelate 1 - 4%"});
   db.nutrition.insert({nutritionId:22,cropName:'lily',nutricient:"Mg",symptoms:"Magnesium deficiency symptoms begin with chlorosis, sometimes with red or orange coloration on the oldest leaves. As symptoms progress the older leaves shrivel and drop, the veins on the remaining leaves stay green and the interveinal areas have an orange chlorotic mottle. Growth can be much reduced.",imageUrl:"",remedy:"Spray of foliage with 1% MgSO4 solution to correct the deficiency."});
   db.nutrition.insert({nutritionId:23,cropName:'lily',nutricient:"S",symptoms:"Symptoms of Sulfur deficiency are much like those caused by Nitrogen: reduced leaf size, stunted growth, chlorosis, orange to purplish pigmentation and delayed maturity",imageUrl:"",remedy:"Sulphur deficiency can be corrected by applying fertilizers containing sulphur like Ammonium sulphate, Sulphate of Potash.Ammonium Sulphate 24% Single Super Phosphate 12% Paramphos 15%"});
   db.nutrition.insert({nutritionId:24,cropName:'lily',nutricient:"Fe",symptoms:"A deficiency of Iron causes a decrease in the size of chloroplasts, reduced chlorophyll and reduced photosynthesis. Symptoms include yellow or white chlorosis between green veins on younger leaves and poor vigor leading to death of the shoot tips. These symptoms are most serious in poorly drained, alkaline soils.",imageUrl:"",remedy:"Apply 10 kg/ha iron sulphate through soil; spray 0.5% FeSO4 + 0.1%citric acid; add 0.2% urea in the spray solution for better results"});
   db.nutrition.insert({nutritionId:25,cropName:'lily',nutricient:"Mn",symptoms:"Symptoms of Manganese deficiency start as interveinal mottled chlorosis, the leaves become yellow and then develop small necrotic lesions in the most chlorotic areas. Reduced leave size and crimping of leaf margins are also possible symptoms",imageUrl:"",remedy:"Apply 10 kg/ha manganese sulphate through soil; foliar application @ 0.12 kg Mn/ha is useful"});
   db.nutrition.insert({nutritionId:26,cropName:'lily',nutricient:"Cu",symptoms:"Copper deficiency occurs in sandy soils of the Southwest. Symptoms are variable but generally consist of a lack of vigor, smaller than normal leaves, and a bluish-green cast to the leaves.",imageUrl:"",remedy:"Small amount of soil applied CuSO4 is able to correct the copper (Cu) deficiency on calcareous soils.Apply 2 - 6 kg Cu / ha as copper sulphate once in 3 - 4 years."});
   db.nutrition.insert({nutritionId:27,cropName:'lily',nutricient:"Zn",symptoms:"Zinc deficiency symptoms begin with interveinal chlorosis. The first leaves in the spring on trees remain small, the stems fail to elongate and the leaves appear to be in whorls or rosettes.",imageUrl:"",remedy:"Apply 15 kg/ha or more Zn through soil; spray 10 kg/ha ZnSO4"});
   db.nutrition.insert({nutritionId:28,cropName:'lily',nutricient:"B",symptoms:"Boron deficiency symptoms vary between plants but some general symptoms are injury to plants meristem and actively dividing tissues and death of the apical meristem. This can lead to a bushy plant habit or the death of all buds preventing new growth",imageUrl:"",remedy:"Spray 10 kg/ha borax or 0.2% borax through soil; foliar application of 0.1 ppm B"});
    
   db.nutrition.insert({nutritionId:29,cropName:'capsicum',nutricient:"N",symptoms:"The symptoms of a nitrogen deficiency are probably the easiest to accurately identify:Older leaves begin to turn yellow, young leaves and shoots will still appear green.Affected leaves will develop a bronze tinge to them.The plant will not grow as quickly as normal and side branches will be stunted giving the plant a thin and slightly sickly appearance.Leaves will fall off earlier than expected.",imageUrl:"",remedy:"For naturally poor soils the best solution is to dig large amounts of well-rotted organic matter into the soil. This will add slow release nitrogen to the soil and improve its ability to make it available to plants. An annual mulch with composted materials will greatly help to maintain the quality of the soil. A quick fix is to apply a general purpose liquid fertiliser where the plants are growing. Don't apply too much however, stick to the dosage rate stated on the packet. Too much nitrogen will result in lots of lush leafy growth at the expense of tomatoes. It can also leave the foliage exposed to wind and rain damage as well as pests and diseases."});
   db.nutrition.insert({nutritionId:30,cropName:'capsicum',nutricient:"Mg",symptoms:"The signs of magnesium deficiency are listed below The leaf tissue of older leaves has yellow / brown blotches in between the leaf veins.The surface of the leaves will become slightly uneven with raised parts showing the worst of the yellowing.Leaves will fall off earlier than expected..",imageUrl:"",remedy:"The long-term solution to a magnesium deficiency is to add Dolomite limestone (readily available at garden centres) to the soil at the dose recommended on the package. Do not exceed the dose because doing so can result in too much calcium which in turn inhibits the roots ability to absorb the magnesium. Dolomite limestone is a slow release product which lasts for a long time in the ground.A more immediate remedy for magnesium deficiency is to spray the foliage with a solution of water and Epsom Salts. The ratio is 20g of Epsom Salts added to a litre of water and a few drop of washing liquid will help the spray to stay on the leaves. Spray again after a fortnight."});
   db.nutrition.insert({nutritionId:31,cropName:'capsicum',nutricient:"K",symptoms:"The signs of potassium deficiency are listed below The edges of older leaves start to turn yellow / light brown New leaves are normal If the deficiency is significant, the yellowing affects the entire leaf (veins are unaffected).",imageUrl:"",remedy:"Add organic matter to the soil at least once a year, mulching with plant material also helps. If organic material is not available blood, fish and bone is a good, long-lasting fertiliser.Quick fixes include liquid tomato plant fertiliser or sulphate of potash."});
    
   db.nutrition.insert({nutritionId:32,cropName:'Broccoli',nutricient:"N",symptoms:"Spindly yellow plants or yellow leaves, sometimes with pink tints.",imageUrl:"",remedy:"In the long term, mulching with organic matter (such as well rotted garden compost or manure) provides a steady trickle of nitrogen to stabilise levels. In the short term, applying high nitrogen fertilisers such as sulphate of ammonia or poultry manure pellets will remedy the problem."});
   db.nutrition.insert({nutritionId:33,cropName:'Broccoli',nutricient:"K",symptoms:"Yellow or purple leaf-tints with browning at the leaf edge and poor flowering or fruiting.",imageUrl:"",remedy:"Apply high potassium fertilisers such as sulphate of potash, tomato feed or certain organic potassium sources derived from sugar beet processing."});
   db.nutrition.insert({nutritionId:34,cropName:'Broccoli',nutricient:"P",symptoms:"Slow growth and dull yellow foliage.",imageUrl:"",remedy:"Apply fertilisers such as superphosphate or bone meal."});
   db.nutrition.insert({nutritionId:35,cropName:'Broccoli',nutricient:"Mg",symptoms:"Yellowing between the leaf veins, sometimes with reddish brown tints and early leaf fall. Magnesium deficiency is common in tomatoes, apples, grape vines, raspberries, roses and rhododendrons.",imageUrl:"",remedy:"In the short term, apply Epsom salts as a foliar feed in summer. Dilute the salts at a rate of 20g of Epsom salts per litre of water (1/3oz per pint) plus a few drops of liquid detergent. Apply two or three times at fortnightly intervals, spraying in dull weather to avoid leaf scorch. In the long term apply to the soil around the roots either Dolomite limestone (calcium-magnesium carbonate) at 100g per sq m (4oz per sq yd) or Epsom salts (magnesium sulphate) at 30g per sq m (1oz per sq yd). Dolomite limestone will make the soil more alkaline, so should not be used around ericaceous (acid-loving) plants such as rhododendrons or camellias, or where the soil is already alkaline."});
   db.nutrition.insert({nutritionId:36,cropName:'Broccoli',nutricient:"Mn",symptoms:"Yellowing between the leaf veins with browning of leaf edges on acid-loving plants.",imageUrl:"",remedy:"Apply chelated iron and manganese treatments, such as Sequestrene, to the soil around the plant roots. "});
   db.nutrition.insert({nutritionId:37,cropName:'Broccoli',nutricient:"Fe",symptoms:"Yellowing between the leaf veins with browning of leaf edges on acid-loving plants.",imageUrl:"",remedy:"Apply chelated iron and manganese treatments, such as Sequestrene, to the soil around the plant roots. "});
   db.nutrition.insert({nutritionId:38,cropName:'Broccoli',nutricient:"B",symptoms:"Stunted growth and tip dieback on lettuce, brown cracks in celery; rotten swedes, turnips and celeriac; dimples in pears with brown patches underneath.",imageUrl:"",remedy:"Treat with fritted trace elements (see our advice on fertilisers) or by applying borax (disodium tetraborate) to the soil before sowing vegetables or as a foliar spray feed applied to pear trees. Soil application rates for borax are: 35g per 20 sq m (1oz per 20 sq yd). Mix well with a large quantity of light sand before spreading so that the chemical is evenly distributed. Foliar spray application rates for borax are: 70g borax in 22-litres water (2½oz in 5 gallons), plus a few drops of detergent to act as a wetting agent, sprayed at petal fall."});
    
   db.nutrition.insert({nutritionId:39,cropName:'Cherry Tomato',nutricient:"N",symptoms:"General yellowing starts on older leaves and then moves gradually upward beacause nitrogen is translocated out of older leaves to the new growth under deficiency",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:40,cropName:'Cherry Tomato',nutricient:"P",symptoms:"Brownish to purplish discolouration along the veins or the under side of the older leaves.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:41,cropName:'Cherry Tomato',nutricient:"K",symptoms:"Marginal necrosis of old leaves.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:42,cropName:'Cherry Tomato',nutricient:"Ca",symptoms:"Extreme yellowing of young leaves.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:43,cropName:'Cherry Tomato',nutricient:"Mg",symptoms:"Interveinal chlorosis on older leaves,leaves get thick and crispy",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:44,cropName:'Cherry Tomato',nutricient:"Fe",symptoms:"Interveinal chlorosis on young leaves,serious deficiency results in a yellowish-white coloring",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:45,cropName:'Cherry Tomato',nutricient:"Zn",symptoms:"Chlorosis,one half of leaf blade ceases to expand and develop while other half is normal i.e. C shaped leaf structure.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:46,cropName:'Cherry Tomato',nutricient:"Mn",symptoms:"Leaves turn yellowish,starting with younger ones;veins remain green,heavy chlorosis.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:47,cropName:'Cherry Tomato',nutricient:"Cu",symptoms:"Chlorosis in younger leaves;flower develops bad.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:48,cropName:'Cherry Tomato',nutricient:"Mo",symptoms:"Chlorosis on the edges of leaves.",imageUrl:"",remedy:""});
   db.nutrition.insert({nutritionId:49,cropName:'Cherry Tomato',nutricient:"B",symptoms:"Bases of younger leaves are black colored.",imageUrl:"",remedy:""});